name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.26
          
          # Optional: working directory, useful for monorepos
          working-directory: src/dining_philosophers/
      
    - name: Build
      run: go build -v src/dining_philosophers/*.go

    - name: Test
      run: go test -v src/dining_philosophers/*.go

